import { QueryDeviceResponse } from '../../models/responses/query-device.response';

export const deviceInfoResponse: QueryDeviceResponse = {
    msg: 'OK',
    code: 200,
    t: 1684756685989,
    data: {
        columns: [
            'time',
            'sys_device_type',
            'manufacturer',
            'serial',
            'dsp1_version',
            'dsp2_version',
            'bms_software_version',
            'ems_hardware_version',
            'sys_run_mode',
            'bat_basic_status',
            'sys_error_code',
            'sys_bat_error_code',
            'sys_error_arm_bit',
            'sys_inv_sink_t',
            'sys_bat_sink_t',
            'pv1_v', // unit 0.1V, 10=1V
            'pv1_i', // unit 0.1A, 10=1A
            'pv2_v', // unit 0.1V, 10=1V
            'pv2_i', // unit 0.1A, 10=1A
            'pv1_p', // W
            'pv2_p', // W
            'ac_v', // unit 0.1V, 10=1V
            'ac_i', // unit 0.1A, 10=1A
            'ac_f', // unit 0.01Hz, 100=1Hz
            'ac_p', // W
            'ac_q', // VA
            'ac_power_factor', // 0.01
            'eps_v', // unit 0.1V, 10=1V
            'eps_i', // unit 0.1A, 10=1A
            'eps_p', // W
            'eps_q', // VA
            'meter_v', // unit 0.1V, 10=1V
            'meter_i', // unit 0.1A, 10=1A
            'meter_f', // unit 0.01Hz, 100=1Hz
            'meter_p', // W
            'meter_q', // VA
            'meter_power_factor', // 0.01
            'bat_v', // unit 0.1V, 10=1V
            'bat_i', // unit 0.01A, 100=1A
            'bat_p', // W
            'bat_soc', // 1
            'bat_soh', // 1
            'bat_voltage_high', // unit 0.001V, 1000=1V
            'bat_voltage_high_id',
            'bat_voltage_low', // unit 0.001V, 1000=1V
            'bat_voltage_low_id',
            'bat_temp_high', // unit 0.1°C，10=1°C
            'bat_temp_high_id',
            'bat_temp_low', // unit 0.1°C，10=1°C
            'bat_temp_low_id',
            'bat_e_total_charge', // unit 0.1kWh, 10=1kWh
            'bat_e_total_discharge', // unit 0.1kWh, 10=1kWh
            'meter_p_pv', // unit 0.1kWh, 10=1kWh
            'electricity_e_total_to_grid', // unit 0.1kWh, 10=1kWh
            'electricity_e_total_from_grid', // unit 0.1kWh, 10=1kWh
            'electricity_e_total_to_grid_pv', // unit 0.1kWh, 10=1kWh
        ],
        metadata: [
            'TIMESTAMP',
            'DOUBLE',
            'VARCHAR',
            'VARCHAR',
            'VARCHAR',
            'VARCHAR',
            'VARCHAR',
            'VARCHAR',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
            'DOUBLE',
        ],
        rows: [
            [
                1684252800000,
                34,
                'WeiHeng',
                'THA133000222344001',
                '510-00001-13',
                '510-10001-10',
                'V0.0',
                '210-60005-00',
                0,
                0,
                11,
                0,
                0,
                38.7,
                36,
                334.8,
                0,
                335.2,
                0,
                0,
                0,
                442.8,
                1.3,
                49.99,
                -601,
                0,
                1,
                0.8,
                0,
                0,
                0,
                233.8,
                0,
                49.98,
                0,
                0,
                1,
                319.2,
                0,
                0,
                85,
                100,
                3.328,
                1,
                3.324,
                1,
                0,
                0,
                0,
                0,
                78974.6,
                65807.3,
                0,
                32.4,
                56.4,
                688138.5,
            ], [
                1684253400000,
                34,
                'WeiHeng',
                'THA133000222344001',
                '510-00001-13',
                '510-10001-10',
                'V0.0',
                '210-60005-00',
                0,
                0,
                11,
                0,
                0,
                46.1,
                36,
                334.8,
                0,
                335.2,
                0,
                0,
                0,
                442.7,
                1.3,
                49.97,
                -601,
                0,
                1,
                0.1,
                0,
                0,
                0,
                231.8,
                0,
                49.96,
                0,
                0,
                1,
                319.2,
                0,
                0,
                22,
                100,
                3.328,
                1,
                3.324,
                1,
                0,
                0,
                0,
                0,
                78974.6,
                65807.3,
                0,
                32.4,
                56.4,
                688138.5,
            ],
        ],
    },
    success: true,
};
